### ISSUE TITLE
Currency select box in user creation page is empty

### ISSUE THREAD

**Issue by juanluisbaptiste** [ladybirdweb/agorainvoicing#744]
Hi,

I'm trying to create am user through the admin panel, but the currency select box does not display any currencies as options to select from:

![screenshot_20190306_234217](https://user-images.githubusercontent.com/2113585/53932814-8e9e6600-4069-11e9-9abe-3f6c4e40eb07.png)

Not allowing to create a new user. 

Latest 1.0.22 release installed.

**Comment by juanluisbaptiste** [comment]
It seems it also happens with Countries in some other places, like Settings -> System Setting.

**Comment by ashu555** [comment]
Hi, juanluisbaptiste, can you please let me know what is your default system currency by going to Settings -> System Setting.

**Comment by juanluisbaptiste** [comment]
Hi @ashu555 , it also appears empty.

**Comment by ashu555** [comment]
It's strange that they appear empty because those values are already seeded in the database. Did you try reinstalling the application?

**Comment by juanluisbaptiste** [comment]
Yes, I deleted the database and started over and the currencies nor in the System settings nor when adding a user appears, neither the Countries on System settings, but they do list when adding a user.

This is the installation log that appears at the end:

https://pastebin.com/nXmS95Jj

**Comment by ashu555** [comment]
Possibilities are, the seeder files are not getting seeded as desired or maybe a server issue. In order to better understand your issue, can we get in touch on Skype, if you use one?
Or I am happy to help you here.

**Comment by juanluisbaptiste** [comment]
for now I think we should continue here so we can leave a record about the issue and its solution. Let me describe what I'm doing. 

I'm setting up docker containers follwing the [apache 2.4 install instructions](https://docs.agorainvoicing.com/installation-with-apache-2-4/). My Dockerfile inherits from the official php-apache image and adds the following:

1. Installs all the modules listed in the [server requirements](https://docs.agorainvoicing.com/server-requirements/) plus mysql and pdo_mysql that aren't mentioned on the documentation (I alread opened another issue for that). 
2. Then download the latest agora version from github, uncompress it and move it to /var/www/html
3. Adds a virtual host apache config copied from the example in the apache install instructions, adjusting _ServerName_, _DocumentRoot_ and _Directory_ directives accordingly (value for the last ones is /var/www/html/public).

After that build and start the service using docker-compose using a separate db and redis containers and then go ahead to the installer at http://localhost/install/.

The installer finishes successfully with the output mentioned in my previous comment, but currencies and the country list in system settings (only  there) appear empty.

Is there a way I could try manually seeding the database from the command line ?

**Comment by ashu555** [comment]
Yeah sure you can, but before that can I see a screenshot of your Settings>System Settings Page. Also, I would like to see all the values that got inserted in the settings table of your DB. And can you check if there are values in your currencies and countries table of your DB?

**Comment by juanluisbaptiste** [comment]
Sstem settings screenshot:

![Screenshot_20190308_155755](https://user-images.githubusercontent.com/2113585/54055397-f0bab080-41ba-11e9-9dee-0c2fd08d3dac.png)

Settings table:

```
MariaDB [agora]> select * from settings\G
*************************** 1. row ***************************
                       id: 1
                  company: Ladybird Web Solution
                  website: https://www.ladybirdweb.com
                    phone: 
                     logo: faveo1.png
                  address: 
                   driver: 
                     host: 
                     port: 0
               encryption: 
                    email: 
                 password: 
                error_log: 1
                  invoice: 8
        subscription_over: 7
subscription_going_to_end: 6
          forgot_password: 5
               order_mail: 4
             welcome_mail: 2
                 download: 9
         invoice_template: 8
              error_email: 
               created_at: 2019-03-08 20:48:15
               updated_at: 2019-03-08 20:48:15
                    state: IN-KA
                     city: Bangalore
                  country: IN
                    title: NULL
               admin_logo: faveo1.png
                 fav_icon: faveo.png
            favicon_title: NULL
            company_email: NULL
     favicon_title_client: NULL
         default_currency: USD
           default_symbol: $
             file_storage: storage/upload
```

And both currencies and countries tables are empty:

![Screenshot_20190308_155409](https://user-images.githubusercontent.com/2113585/54055706-dcc37e80-41bb-11e9-997b-28512c306533.png)
